language: node_js
node_js:
- 0.10.28
branches:
  only:
  - master
before_script:
- npm install grunt-cli
- ./node_modules/.bin/grunt build
notifications:
  email:
    recipients:
    - constantx@gmail.com
    on_success: change
    on_failure: always
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then
  NODE_ENV=production ./node_modules/.bin/grunt travis; fi
skip_cleanup: true
env:
  global:
    secure: IE5UC2CHE3nQSeMGL/N+25A0D1hzIN9nbRKHmLqz32j5p4hE0CBMtbVTILcBwWbMR+Mgi3RUqKpuqb3SsyncEDEmoEdqhs2zIwBsDv+KrMMhqg68yNa8wOdShfxTpaXKIDe+f/Ml1ETPKcHLQknYLIvXBCP34uRQ74Afe7DHT9E=
